npmScopes:
  mis:
    npmRegistryServer: 'http://git.wrapsody.fasoo.com/api/v4/projects/442/packages/npm/'
    npmAuthToken: '3JgiQ1wohNNM6zA98Jj9'

unsafeHttpWhitelist: # yarn berry에서 안전하지 않은 http 요청을 예외로 허용함.
  - git.wrapsody.fasoo.com

checksumBehavior: 'ignore'
